name: Automated Cloud Security Scanner

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  AWS_S3_BUCKET: secure-web-scan-results
  AWS_REGION: us-east-2

jobs:
  setup_environment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: GitHubActionsSession

      - name: Verify AWS Credentials
        run: aws sts get-caller-identity

      - name: Install Snyk CLI
        run: |
          curl -Lo snyk https://github.com/snyk/snyk/releases/latest/download/snyk-linux
          chmod +x snyk
          sudo mv snyk /usr/local/bin/

      - name: Authenticate Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Build Docker Image in GitHub Actions
        run: docker build -t vulnerable-app .

      - name: Run Snyk Container Scan
        continue-on-error: true
        run: |
          mkdir -p output  # Ensure the output directory exists
          snyk container test vulnerable-app --json > output/snyk_container_results.json || \
          (echo "⚠️ Snyk scan failed or found no vulnerabilities" && touch output/snyk_container_results.json)

      - name: Upload Scan Results to AWS S3
        run: |
          if [ -f output/snyk_container_results.json ]; then
            aws s3 cp output/snyk_container_results.json s3://${{ env.AWS_S3_BUCKET }}/snyk_container_results.json
          else
            echo "❌ Snyk scan report not found, skipping upload."
          fi
