name: Secure Web Security Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  security_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Verify Target URL is Reachable
        run: |
          curl -I http://172.31.14.30:3000 || (echo "ERROR: Target URL is not reachable!" && exit 1)

      - name: Pull Latest OWASP ZAP Image
        run: docker pull ghcr.io/zaproxy/zaproxy:2.11.1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::615299768374:role/GitHubActionsSecurityRole
          aws-region: us-east-2

      - name: Run OWASP ZAP Scan (Optimized)
        run: |
          docker run --rm --memory=2g ghcr.io/zaproxy/zaproxy:2.11.1 zap.sh \
          -cmd "-config scanner.attackMode=off -config passiveScan.enable=true -config spider.maxDepth=1 -config ajaxSpider.enable=false -config passiveScan.maxAlertsPerRule=3 -config connection.requestTimeout=5000 -config connection.timeoutInSecs=10 -config scanner.threadPerHost=1 -config api.disablekey=true" \
          -url http://172.31.14.30:3000

      - name: Upload OWASP ZAP Scan Results to AWS S3
        if: success()
        run: |
          aws s3 cp /zap/wrk/output/zap_report.html s3://secure-web-scan-results/zap_report.html

      - name: Install Snyk CLI
        run: |
          curl -Lo snyk https://github.com/snyk/snyk/releases/latest/download/snyk-linux
          chmod +x snyk
          mv snyk /usr/local/bin/

      - name: Run Optimized Snyk Dependency Scan
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          snyk test --file=requirements.txt --fail-on=upgradable --severity-threshold=high --prune-repeated-subdependencies --json | tee snyk_scan.json

      - name: Upload Snyk Scan Results to AWS S3
        if: success()
        run: |
          aws s3 cp snyk_scan.json s3://secure-web-scan-results/snyk_scan.json
