name: Secure Web Security Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  security_scan:
    runs-on: ubuntu-latest
    timeout-minutes: 3  # Allow the full job to run for 3 minutes max but do not cancel prematurely

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::615299768374:role/GitHubActionsSecurityRole
          aws-region: us-east-2

      - name: Test Connection to EC2 (Ensure GitHub Actions Can Reach the App)
        run: curl -I http://172.31.14.30:3000 || echo "Failed to connect"

      - name: Run OWASP ZAP Scan on Private App (Fixed Time Limit)
        uses: zaproxy/action-full-scan@v0.5.0
        with:
          target: 'http://172.31.14.30:3000'
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          rules_file_name: ''
          cmd_options: '-m 1 -T 2 -r zap_report.html -z "-config spider.maxDuration=2 -config spider.maxDepth=1 -config scanner.threadPerHost=1"'

      - name: Run Snyk Dependency Scan (Fast Mode)
        uses: snyk/actions/python@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --fail-on=upgradable --severity-threshold=high --prune-repeated-subdependencies --timeout=90

      - name: Upload Scan Results to AWS S3
        run: |
          aws s3 cp zap_scan.json s3://secure-web-scan-results/zap_scan.json
          aws s3 cp snyk_scan.json s3://secure-web-scan-results/snyk_scan.json
