name: Secure Web Security Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  security_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::615299768374:role/GitHubActionsSecurityRole
          aws-region: us-east-2

      - name: Create Output Directory
        run: mkdir -p output

      - name: Run OWASP ZAP Scan in Headless Mode
        run: |
          docker run --rm -v $(pwd)/output:/zap/wrk ghcr.io/zaproxy/zaproxy:stable zap.sh \
            -cmd -quickurl http://3.129.253.217:3000 -quickout /zap/wrk/zap_report.html

      - name: Verify Scan Report Exists
        run: ls -lh output && cat output/zap_report.html || (echo "❌ Report file missing" && exit 1)

      - name: Upload Scan Results to AWS S3
        run: aws s3 cp output/zap_report.html s3://secure-web-scan-results/zap_report.html
