name: Secure Web Security Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  setup_environment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4  # Updated to v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::615299768374:role/GitHubActionsSecurityRole
          aws-region: us-east-2

      - name: Verify AWS Credentials
        run: aws sts get-caller-identity

      - name: Create Output Directory
        run: mkdir -p output

      - name: Install Snyk CLI
        run: |
          curl -Lo snyk https://github.com/snyk/snyk/releases/latest/download/snyk-linux
          chmod +x snyk
          sudo mv snyk /usr/local/bin/

      - name: Authenticate Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Run Snyk Code Scan (Static Analysis)
        continue-on-error: true
        run: snyk code test --json > output/snyk_code_results.json

      - name: Run Snyk Dependency Scan
        continue-on-error: true
        run: snyk test --all-projects --json > output/snyk_dependency_results.json

      - name: Run Snyk Container Scan (if using Docker)
        continue-on-error: true
        run: snyk container test your-docker-image:latest --json > output/snyk_container_results.json || echo "No container image found."

      - name: Upload Snyk Scan Reports as Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: snyk_scan_reports
          path: output/
          compression-level: 0  # Prevents unnecessary compression

  upload_results:
    runs-on: ubuntu-latest
    needs: setup_environment

    steps:
      - name: Download Scan Reports
        uses: actions/download-artifact@v4
        with:
          name: snyk_scan_reports
          path: output

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::615299768374:role/GitHubActionsSecurityRole
          aws-region: us-east-2

      - name: Upload Scan Results to AWS S3
        run: |
          aws s3 cp output/snyk_code_results.json s3://secure-web-scan-results/snyk_code_results.json
          aws s3 cp output/snyk_dependency_results.json s3://secure-web-scan-results/snyk_dependency_results.json
          aws s3 cp output/snyk_container_results.json s3://secure-web-scan-results/snyk_container_results.json || echo "No container scan results to upload."
