name: Secure Web Security Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  setup_environment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Check Docker Installation
        run: |
          docker --version || echo "❌ Docker is not installed!"
          docker info || echo "❌ Docker is not running!"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::615299768374:role/GitHubActionsSecurityRole
          aws-region: us-east-2

      - name: Check EC2 Connection
        run: curl -I http://3.129.253.217:3000 || echo "❌ Failed to connect to EC2"

      - name: Run OWASP ZAP Scan
        run: |
          docker pull ghcr.io/zaproxy/zaproxy:stable
          docker run --rm -v $(pwd):/zap/wrk ghcr.io/zaproxy/zaproxy:stable zap.sh \
            -quickurl http://3.129.253.217:3000 \
            -quickprogress \
            -quickout /zap/wrk/output/zap_report.html \
            -cmd \
            -config scanner.attackMode=false \
            -config passiveScan.enable=true \
            -config spider.maxDepth=1 \
            -config ajaxSpider.enable=false \
            -config passiveScan.maxAlertsPerRule=3 \
            -config api.debug=false \
            -config connection.requestTimeout=2000 \
            -config connection.timeoutInSecs=5 \
            -config scanner.threadPerHost=1

  upload_results:
    runs-on: ubuntu-latest
    needs: setup_environment

    steps:
      - name: Upload Scan Results to AWS S3
        run: |
          aws s3 cp /zap/wrk/output/zap_report.html s3://secure-web-scan-results/zap_report.html
