name: Secure Web Security Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  SCAN_URL: http://3.129.253.217:3000
  AWS_S3_BUCKET: secure-web-scan-results
  AWS_REGION: us-east-2

jobs:
  security_scan:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::615299768374:role/GitHubActionsSecurityRole
          aws-region: ${{ env.AWS_REGION }}

      - name: Install ZAP CLI
        run: |
          pip install zapcli

      - name: Create Output Directory
        run: mkdir -p output

      - name: Start OWASP ZAP in Daemon Mode
        run: |
          docker run -d --name zap -p 8080:8080 -v $(pwd)/output:/zap/wrk \
            ghcr.io/zaproxy/zaproxy:stable zap.sh -daemon -host 0.0.0.0 -port 8080

      - name: Wait for ZAP to Start
        run: |
          for i in {1..10}; do
            if zap-cli --zap-url http://localhost:8080 healthcheck --timeout 60; then
              echo "✅ ZAP is ready!"
              break
            fi
            echo "⏳ Waiting for ZAP to be available ($i/10)..."
            docker logs zap
            sleep 6
            if [ $i -eq 10 ]; then
              echo "❌ ZAP failed to start"
              exit 1
            fi
          done

      - name: Run Quick Scan via ZAP CLI
        run: |
          echo "Starting quick scan on ${{ env.SCAN_URL }}..."
          zap-cli --zap-url http://localhost:8080 quick-scan --spider --scanners all ${{ env.SCAN_URL }}
          echo "✅ Scan completed!"

      - name: Generate ZAP Report
        run: |
          echo "Generating ZAP report..."
          zap-cli --zap-url http://localhost:8080 report -o output/zap_report.html -f html

      - name: Stop OWASP ZAP
        run: docker stop zap

      - name: Verify Scan Report Exists
        run: ls -lh output && cat output/zap_report.html || (echo "❌ Report file missing" && exit 1)

      - name: Upload Scan Results to AWS S3
        if: success()
        run: aws s3 cp output/zap_report.html s3://${{ env.AWS_S3_BUCKET }}/zap_report.html
