name: Secure Web Security Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  security_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::615299768374:role/GitHubActionsSecurityRole
          aws-region: us-east-2

      - name: Test Connection to EC2 (Ensure GitHub Actions Can Reach the App)
        run: curl -I http://172.31.14.30:3000 || echo "Failed to connect"

      - name: Run OWASP ZAP API Scan (Faster)
        uses: zaproxy/action-api-scan@v0.5.0
        with:
          target: 'http://172.31.14.30:3000'
          format: 'html'
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          cmd_options: >-
            -z "-config scanner.attackMode=off
                -config passiveScan.enable=true
                -config spider.maxDepth=1
                -config ajaxSpider.enable=false
                -config passiveScan.maxAlertsPerRule=1
                -config connection.requestTimeout=2000
                -config connection.timeoutInSecs=5
                -config scanner.threadPerHost=1"

      - name: Run Snyk Dependency Scan (Faster)
        uses: snyk/actions/python@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --file=requirements.txt --fail-on=upgradable --severity-threshold=high --prune-repeated-subdependencies --strict-out-of-sync=false

      - name: Upload Scan Results to AWS S3
        run: |
          aws s3 cp /zap/wrk/output/zap_report.html s3://secure-web-scan-results/zap_report.html
          aws s3 cp snyk_scan.json s3://secure-web-scan-results/snyk_scan.json
