name: Secure Web Security Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  security_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Docker
        run: |
          sudo systemctl start docker
          sudo systemctl enable docker
          sudo usermod -aG docker $USER
          sudo chmod 666 /var/run/docker.sock
          docker --version
          docker run hello-world

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::615299768374:role/GitHubActionsSecurityRole
          aws-region: us-east-2

      - name: Test Connection to EC2
        run: curl -I http://3.129.253.217:3000 || echo "Failed to connect"

      - name: Run OWASP ZAP Scan
        uses: zaproxy/action-full-scan@v0.5.0
        with:
          target: 'http://3.129.253.217:3000'
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          cmd_options: '-m 0 -r /zap/wrk/output/zap_report.html -z "-config scanner.attackMode=off -config passiveScan.enable=true -config spider.maxDepth=1 -config ajaxSpider.enable=false -config passiveScan.maxAlertsPerRule=3 -config api.debug=false -config connection.requestTimeout=2000 -config connection.timeoutInSecs=5 -config scanner.threadPerHost=1"'

      - name: Upload Scan Results to AWS S3
        run: |
          aws s3 cp /zap/wrk/output/zap_report.html s3://secure-web-scan-results/zap_report.html
